import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'

/** components */
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable'
import { Header } from '@/app/_components/header'
import { Sidebar } from '@/app/_components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className="dark"
    >
      <body className={inter.className}>
        <div className="flex h-[100dvh] flex-col">
          <Header />
          <ResizablePanelGroup direction="horizontal">
            <Sidebar />
            <ResizableHandle />
            <ResizablePanel defaultSize={81.5}>{children}</ResizablePanel>
          </ResizablePanelGroup>
        </div>
      </body>
    </html>
  )
}
